// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package memdb

import (
	"context"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
    scope, repo_key, id, category, title, content, pinned, embedding,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
) RETURNING scope, repo_key, id, category, title, content, pinned, use_count, last_used_at, embedding, created_at, updated_at
`

type CreateMemoryParams struct {
	Scope     string `json:"scope"`
	RepoKey   string `json:"repo_key"`
	ID        string `json:"id"`
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Pinned    int64  `json:"pinned"`
	Embedding []byte `json:"embedding"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, createMemory,
		arg.Scope,
		arg.RepoKey,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.Embedding,
	)
	var i Memory
	err := row.Scan(
		&i.Scope,
		&i.RepoKey,
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE scope = ? AND repo_key = ? AND id = ?
`

type DeleteMemoryParams struct {
	Scope   string `json:"scope"`
	RepoKey string `json:"repo_key"`
	ID      string `json:"id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemory, arg.Scope, arg.RepoKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemory = `-- name: GetMemory :one
SELECT scope, repo_key, id, category, title, content, pinned, use_count, last_used_at, embedding, created_at, updated_at FROM memories
WHERE scope = ? AND repo_key = ? AND id = ?
LIMIT 1
`

type GetMemoryParams struct {
	Scope   string `json:"scope"`
	RepoKey string `json:"repo_key"`
	ID      string `json:"id"`
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, arg.Scope, arg.RepoKey, arg.ID)
	var i Memory
	err := row.Scan(
		&i.Scope,
		&i.RepoKey,
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryByTitle = `-- name: GetMemoryByTitle :one
SELECT scope, repo_key, id, category, title, content, pinned, use_count, last_used_at, embedding, created_at, updated_at FROM memories
WHERE scope = ? AND repo_key = ? AND lower(title) = lower(?)
LIMIT 1
`

type GetMemoryByTitleParams struct {
	Scope   string `json:"scope"`
	RepoKey string `json:"repo_key"`
	LOWER   string `json:"LOWER"`
}

func (q *Queries) GetMemoryByTitle(ctx context.Context, arg GetMemoryByTitleParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemoryByTitle, arg.Scope, arg.RepoKey, arg.LOWER)
	var i Memory
	err := row.Scan(
		&i.Scope,
		&i.RepoKey,
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importMemory = `-- name: ImportMemory :exec
INSERT INTO memories (
    scope, repo_key, id, category, title, content, pinned, use_count,
    last_used_at, embedding, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (scope, repo_key, id) DO UPDATE SET
    category = excluded.category,
    title = excluded.title,
    content = excluded.content,
    pinned = excluded.pinned,
    use_count = excluded.use_count,
    last_used_at = excluded.last_used_at,
    embedding = excluded.embedding,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
`

type ImportMemoryParams struct {
	Scope      string `json:"scope"`
	RepoKey    string `json:"repo_key"`
	ID         string `json:"id"`
	Category   string `json:"category"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Pinned     int64  `json:"pinned"`
	UseCount   int64  `json:"use_count"`
	LastUsedAt int64  `json:"last_used_at"`
	Embedding  []byte `json:"embedding"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

// Writes a memory carried over from a per-workspace database with the
// usage and timestamps it had there.
func (q *Queries) ImportMemory(ctx context.Context, arg ImportMemoryParams) error {
	_, err := q.db.ExecContext(ctx, importMemory,
		arg.Scope,
		arg.RepoKey,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.UseCount,
		arg.LastUsedAt,
		arg.Embedding,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listLegacyImports = `-- name: ListLegacyImports :many
SELECT source FROM legacy_imports ORDER BY source
`

func (q *Queries) ListLegacyImports(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var source string
		if err := rows.Scan(&source); err != nil {
			return nil, err
		}
		items = append(items, source)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleMemories = `-- name: ListVisibleMemories :many
SELECT scope, repo_key, id, category, title, content, pinned, use_count, last_used_at, embedding, created_at, updated_at FROM memories
WHERE scope = 'global' OR (scope = 'repo' AND repo_key = ?1)
ORDER BY scope = 'repo', pinned DESC, updated_at DESC, id ASC
`

// The memories one workspace sees: every global memory and those of its
// repository, global first. The id tie-breaks: updated_at has
// whole-second resolution, so memories saved in the same second would
// otherwise come back in whatever order SQLite chose, and the index the
// model reads would reshuffle between runs.
func (q *Queries) ListVisibleMemories(ctx context.Context, repoKey string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleMemories, repoKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.Scope,
			&i.RepoKey,
			&i.ID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.Pinned,
			&i.UseCount,
			&i.LastUsedAt,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapMemories = `-- name: ReapMemories :execrows
DELETE FROM memories
WHERE memories.scope = ?1 AND memories.repo_key = ?2
  AND memories.pinned = 0
  AND memories.rowid NOT IN (
    SELECT kept.rowid FROM memories AS kept
    WHERE kept.scope = ?1 AND kept.repo_key = ?2
    ORDER BY kept.pinned DESC, kept.use_count DESC, kept.last_used_at DESC,
             kept.updated_at DESC, kept.rowid DESC, kept.id ASC
    LIMIT ?3
)
`

type ReapMemoriesParams struct {
	Scope   string `json:"scope"`
	RepoKey string `json:"repo_key"`
	Keep    int64  `json:"keep"`
}

// Keeps the max_memories most useful memories of one scope (global, or
// one repository) and deletes the unpinned rest.
func (q *Queries) ReapMemories(ctx context.Context, arg ReapMemoriesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapMemories, arg.Scope, arg.RepoKey, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordLegacyImport = `-- name: RecordLegacyImport :exec
INSERT INTO legacy_imports (source, memories, imported_at)
VALUES (?, ?, strftime('%s', 'now'))
ON CONFLICT (source) DO NOTHING
`

type RecordLegacyImportParams struct {
	Source   string `json:"source"`
	Memories int64  `json:"memories"`
}

func (q *Queries) RecordLegacyImport(ctx context.Context, arg RecordLegacyImportParams) error {
	_, err := q.db.ExecContext(ctx, recordLegacyImport, arg.Source, arg.Memories)
	return err
}

const touchMemory = `-- name: TouchMemory :exec
UPDATE memories SET use_count = use_count + 1, last_used_at = strftime('%s', 'now')
WHERE scope = ? AND repo_key = ? AND id = ?
`

type TouchMemoryParams struct {
	Scope   string `json:"scope"`
	RepoKey string `json:"repo_key"`
	ID      string `json:"id"`
}

func (q *Queries) TouchMemory(ctx context.Context, arg TouchMemoryParams) error {
	_, err := q.db.ExecContext(ctx, touchMemory, arg.Scope, arg.RepoKey, arg.ID)
	return err
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET
    category = ?,
    title = ?,
    content = ?,
    pinned = ?,
    embedding = ?,
    updated_at = strftime('%s', 'now')
WHERE scope = ? AND repo_key = ? AND id = ?
RETURNING scope, repo_key, id, category, title, content, pinned, use_count, last_used_at, embedding, created_at, updated_at
`

type UpdateMemoryParams struct {
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Pinned    int64  `json:"pinned"`
	Embedding []byte `json:"embedding"`
	Scope     string `json:"scope"`
	RepoKey   string `json:"repo_key"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, updateMemory,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.Embedding,
		arg.Scope,
		arg.RepoKey,
		arg.ID,
	)
	var i Memory
	err := row.Scan(
		&i.Scope,
		&i.RepoKey,
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
