// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memdb

type LegacyImport struct {
	Source     string `json:"source"`
	Memories   int64  `json:"memories"`
	ImportedAt int64  `json:"imported_at"`
}

type MemoriesFt struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Memory struct {
	Scope      string `json:"scope"`
	RepoKey    string `json:"repo_key"`
	ID         string `json:"id"`
	Category   string `json:"category"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	Pinned     int64  `json:"pinned"`
	UseCount   int64  `json:"use_count"`
	LastUsedAt int64  `json:"last_used_at"`
	Embedding  []byte `json:"embedding"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}
