// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memdb

import (
	"context"
)

type Querier interface {
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error)
	GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error)
	GetMemoryByTitle(ctx context.Context, arg GetMemoryByTitleParams) (Memory, error)
	// Writes a memory carried over from a per-workspace database with the
	// usage and timestamps it had there.
	ImportMemory(ctx context.Context, arg ImportMemoryParams) error
	ListLegacyImports(ctx context.Context) ([]string, error)
	// The memories one workspace sees: every global memory and those of its
	// repository, global first. The id tie-breaks: updated_at has
	// whole-second resolution, so memories saved in the same second would
	// otherwise come back in whatever order SQLite chose, and the index the
	// model reads would reshuffle between runs.
	ListVisibleMemories(ctx context.Context, repoKey string) ([]Memory, error)
	// Keeps the max_memories most useful memories of one scope (global, or
	// one repository) and deletes the unpinned rest.
	ReapMemories(ctx context.Context, arg ReapMemoriesParams) (int64, error)
	RecordLegacyImport(ctx context.Context, arg RecordLegacyImportParams) error
	TouchMemory(ctx context.Context, arg TouchMemoryParams) error
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error)
}

var _ Querier = (*Queries)(nil)
