// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package db

import (
	"context"
)

const createCheckpoint = `-- name: CreateCheckpoint :one
INSERT INTO checkpoints (
    id,
    session_id,
    message_id,
    commit_sha,
    created_at
) VALUES (
    ?, ?, ?, ?, strftime('%s', 'now')
)
ON CONFLICT(session_id, message_id) DO UPDATE SET
    commit_sha = excluded.commit_sha
RETURNING id, session_id, message_id, commit_sha, created_at
`

type CreateCheckpointParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
	CommitSha string `json:"commit_sha"`
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, createCheckpoint,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.CommitSha,
	)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpointByMessage = `-- name: GetCheckpointByMessage :one
SELECT id, session_id, message_id, commit_sha, created_at
FROM checkpoints
WHERE message_id = ? LIMIT 1
`

func (q *Queries) GetCheckpointByMessage(ctx context.Context, messageID string) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointByMessage, messageID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckpointsBySession = `-- name: ListCheckpointsBySession :many
SELECT id, session_id, message_id, commit_sha, created_at
FROM checkpoints
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListCheckpointsBySession(ctx context.Context, sessionID string) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
