// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package db

import (
	"context"
)

const countMemories = `-- name: CountMemories :one
SELECT COUNT(*) FROM memories
`

func (q *Queries) CountMemories(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countMemoriesStmt, countMemories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
    id, category, title, content, pinned, embedding, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
) RETURNING id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at, embedding
`

type CreateMemoryParams struct {
	ID        string `json:"id"`
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Pinned    int64  `json:"pinned"`
	Embedding []byte `json:"embedding"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.createMemoryStmt, createMemory,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.Embedding,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteMemoryStmt, deleteMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemory = `-- name: GetMemory :one
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at, embedding FROM memories WHERE id = ? LIMIT 1
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.queryRow(ctx, q.getMemoryStmt, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
	)
	return i, err
}

const getMemoryByTitle = `-- name: GetMemoryByTitle :one
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at, embedding FROM memories WHERE lower(title) = lower(?) LIMIT 1
`

func (q *Queries) GetMemoryByTitle(ctx context.Context, lower string) (Memory, error) {
	row := q.queryRow(ctx, q.getMemoryByTitleStmt, getMemoryByTitle, lower)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at, embedding FROM memories
ORDER BY pinned DESC, updated_at DESC, id ASC
`

// The id tie-breaks: updated_at has whole-second resolution, so
// memories saved in the same second would otherwise come back in
// whatever order SQLite chose, and the index the model reads would
// reshuffle between runs.
func (q *Queries) ListMemories(ctx context.Context) ([]Memory, error) {
	rows, err := q.query(ctx, q.listMemoriesStmt, listMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.Pinned,
			&i.UseCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapMemories = `-- name: ReapMemories :execrows
DELETE FROM memories
WHERE pinned = 0 AND id NOT IN (
    SELECT id FROM memories
    ORDER BY pinned DESC, use_count DESC, last_used_at DESC,
             updated_at DESC, rowid DESC, id ASC
    LIMIT ?
)
`

func (q *Queries) ReapMemories(ctx context.Context, limit int64) (int64, error) {
	result, err := q.exec(ctx, q.reapMemoriesStmt, reapMemories, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchMemory = `-- name: TouchMemory :exec
UPDATE memories SET use_count = use_count + 1, last_used_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) TouchMemory(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.touchMemoryStmt, touchMemory, id)
	return err
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET
    category = ?,
    title = ?,
    content = ?,
    pinned = ?,
    embedding = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at, embedding
`

type UpdateMemoryParams struct {
	Category  string `json:"category"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Pinned    int64  `json:"pinned"`
	Embedding []byte `json:"embedding"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.updateMemoryStmt, updateMemory,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.Embedding,
		arg.ID,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Embedding,
	)
	return i, err
}
