// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package db

import (
	"context"
	"database/sql"
)

const countMemories = `-- name: CountMemories :one
SELECT COUNT(*) FROM memories
`

func (q *Queries) CountMemories(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countMemoriesStmt, countMemories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
    id, category, title, content, pinned, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
) RETURNING id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at
`

type CreateMemoryParams struct {
	ID       string `json:"id"`
	Category string `json:"category"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Pinned   int64  `json:"pinned"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.createMemoryStmt, createMemory,
		arg.ID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteMemoryStmt, deleteMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemory = `-- name: GetMemory :one
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at FROM memories WHERE id = ? LIMIT 1
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.queryRow(ctx, q.getMemoryStmt, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryByTitle = `-- name: GetMemoryByTitle :one
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at FROM memories WHERE lower(title) = lower(?) LIMIT 1
`

func (q *Queries) GetMemoryByTitle(ctx context.Context, lower string) (Memory, error) {
	row := q.queryRow(ctx, q.getMemoryByTitleStmt, getMemoryByTitle, lower)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at FROM memories
ORDER BY pinned DESC, updated_at DESC
`

func (q *Queries) ListMemories(ctx context.Context) ([]Memory, error) {
	rows, err := q.query(ctx, q.listMemoriesStmt, listMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.Pinned,
			&i.UseCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapMemories = `-- name: ReapMemories :execrows
DELETE FROM memories
WHERE pinned = 0 AND id NOT IN (
    SELECT id FROM memories
    ORDER BY pinned DESC, use_count DESC, last_used_at DESC,
             updated_at DESC, rowid DESC
    LIMIT ?
)
`

func (q *Queries) ReapMemories(ctx context.Context, limit int64) (int64, error) {
	result, err := q.exec(ctx, q.reapMemoriesStmt, reapMemories, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at FROM memories
WHERE title LIKE '%' || ? || '%' OR content LIKE '%' || ? || '%'
ORDER BY pinned DESC, updated_at DESC
`

type SearchMemoriesParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]Memory, error) {
	rows, err := q.query(ctx, q.searchMemoriesStmt, searchMemories, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.Pinned,
			&i.UseCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMemory = `-- name: TouchMemory :exec
UPDATE memories SET use_count = use_count + 1, last_used_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) TouchMemory(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.touchMemoryStmt, touchMemory, id)
	return err
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET
    category = ?,
    title = ?,
    content = ?,
    pinned = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
RETURNING id, category, title, content, pinned, use_count, last_used_at, created_at, updated_at
`

type UpdateMemoryParams struct {
	Category string `json:"category"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Pinned   int64  `json:"pinned"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.queryRow(ctx, q.updateMemoryStmt, updateMemory,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.Pinned,
		arg.ID,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.UseCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
