// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    model,
    provider,
    is_summary_message,
    visible,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, prism_model_id, prism_model_name, prism_hypercredit_savings, prism_dollar_savings, visible
`

type CreateMessageParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
	Visible          int64          `json:"visible"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.IsSummaryMessage,
		arg.Visible,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.PrismModelID,
		&i.PrismModelName,
		&i.PrismHypercreditSavings,
		&i.PrismDollarSavings,
		&i.Visible,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteMessagesFrom = `-- name: DeleteMessagesFrom :many
DELETE FROM messages
WHERE messages.session_id = ?1
  AND (messages.created_at, messages.rowid) >= (
    SELECT a.created_at, a.rowid FROM messages a
    WHERE a.id = ?2 AND a.session_id = ?1
  )
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, prism_model_id, prism_model_name, prism_hypercredit_savings, prism_dollar_savings, visible
`

type DeleteMessagesFromParams struct {
	SessionID string `json:"session_id"`
	AnchorID  string `json:"anchor_id"`
}

// Deletes the anchor message and every message after it in the session,
// in the order ListMessagesBySession reads them, as one statement.
func (q *Queries) DeleteMessagesFrom(ctx context.Context, arg DeleteMessagesFromParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, deleteMessagesFrom, arg.SessionID, arg.AnchorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.PrismModelID,
			&i.PrismModelName,
			&i.PrismHypercreditSavings,
			&i.PrismDollarSavings,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastAssistantMessageBySession = `-- name: GetLastAssistantMessageBySession :one
SELECT provider, model
FROM messages
WHERE session_id = ? AND role = 'assistant' AND is_summary_message = 0
ORDER BY created_at DESC, rowid DESC
LIMIT 1
`

type GetLastAssistantMessageBySessionRow struct {
	Provider sql.NullString `json:"provider"`
	Model    sql.NullString `json:"model"`
}

// Only the provider and model of the last assistant message are read;
// skip fetching the parts blob and the rest of the row.
func (q *Queries) GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (GetLastAssistantMessageBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getLastAssistantMessageBySession, sessionID)
	var i GetLastAssistantMessageBySessionRow
	err := row.Scan(&i.Provider, &i.Model)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, prism_model_id, prism_model_name, prism_hypercredit_savings, prism_dollar_savings, visible
FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.PrismModelID,
		&i.PrismModelName,
		&i.PrismHypercreditSavings,
		&i.PrismDollarSavings,
		&i.Visible,
	)
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, prism_model_id, prism_model_name, prism_hypercredit_savings, prism_dollar_savings, visible
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC, rowid ASC
`

// created_at has whole-second resolution and a prompt and its reply
// often share a second; rowid is insertion order and breaks the tie.
func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.PrismModelID,
			&i.PrismModelName,
			&i.PrismHypercreditSavings,
			&i.PrismDollarSavings,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionFrom = `-- name: ListMessagesBySessionFrom :many
SELECT m.id, m.session_id, m.role, m.parts, m.model, m.created_at, m.updated_at, m.finished_at, m.provider, m.is_summary_message, m.prism_model_id, m.prism_model_name, m.prism_hypercredit_savings, m.prism_dollar_savings, m.visible
FROM messages m
WHERE m.session_id = ?
  AND m.created_at >= (SELECT b.created_at FROM messages b WHERE b.id = ?)
ORDER BY m.created_at ASC, m.rowid ASC
`

type ListMessagesBySessionFromParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) ListMessagesBySessionFrom(ctx context.Context, arg ListMessagesBySessionFromParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySessionFrom, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.PrismModelID,
			&i.PrismModelName,
			&i.PrismHypercreditSavings,
			&i.PrismDollarSavings,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptHistory = `-- name: ListPromptHistory :many
SELECT
    CAST(json_extract(p.value, '$.type') AS TEXT) AS part_type,
    CAST(COALESCE(json_extract(p.value, '$.data.text'), json_extract(p.value, '$.data.command'), '') AS TEXT) AS entry
FROM messages m, json_each(m.parts) p
WHERE m.role = 'user'
  AND (?1 = '' OR m.session_id = ?1)
  AND json_extract(p.value, '$.type') IN ('text', 'shell_command')
ORDER BY m.created_at DESC, m.rowid DESC, p.key ASC
`

type ListPromptHistoryRow struct {
	PartType string `json:"part_type"`
	Entry    string `json:"entry"`
}

// The prompt-history entries of user messages, newest message first: each
// text part as written and each shell command prefixed with "!", read
// straight from the stored parts so no binary attachment or context note
// is decoded. An empty session_id reads every session.
func (q *Queries) ListPromptHistory(ctx context.Context, sessionID interface{}) ([]ListPromptHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPromptHistory, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromptHistoryRow{}
	for rows.Next() {
		var i ListPromptHistoryRow
		if err := rows.Scan(&i.PartType, &i.Entry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesBySession = `-- name: ListUserMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, prism_model_id, prism_model_name, prism_hypercredit_savings, prism_dollar_savings, visible
FROM messages
WHERE session_id = ? AND role = 'user'
ORDER BY created_at DESC, rowid DESC
`

func (q *Queries) ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listUserMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.PrismModelID,
			&i.PrismModelName,
			&i.PrismHypercreditSavings,
			&i.PrismDollarSavings,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    prism_model_id = ?,
    prism_model_name = ?,
    prism_hypercredit_savings = ?,
    prism_dollar_savings = ?,
    finished_at = ?,
    visible = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts                   string          `json:"parts"`
	PrismModelID            sql.NullString  `json:"prism_model_id"`
	PrismModelName          sql.NullString  `json:"prism_model_name"`
	PrismHypercreditSavings sql.NullFloat64 `json:"prism_hypercredit_savings"`
	PrismDollarSavings      sql.NullFloat64 `json:"prism_dollar_savings"`
	FinishedAt              sql.NullInt64   `json:"finished_at"`
	Visible                 int64           `json:"visible"`
	ID                      string          `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateMessage,
		arg.Parts,
		arg.PrismModelID,
		arg.PrismModelName,
		arg.PrismHypercreditSavings,
		arg.PrismDollarSavings,
		arg.FinishedAt,
		arg.Visible,
		arg.ID,
	)
	return err
}
