// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_catalog.sql

package db

import (
	"context"
)

const getModelCatalog = `-- name: GetModelCatalog :one
SELECT id, data, fetched_at FROM model_catalog WHERE id = 1
`

func (q *Queries) GetModelCatalog(ctx context.Context) (ModelCatalog, error) {
	row := q.db.QueryRowContext(ctx, getModelCatalog)
	var i ModelCatalog
	err := row.Scan(&i.ID, &i.Data, &i.FetchedAt)
	return i, err
}

const saveModelCatalog = `-- name: SaveModelCatalog :one
INSERT INTO model_catalog (id, data, fetched_at)
VALUES (1, ?, strftime('%s', 'now'))
ON CONFLICT (id) DO UPDATE SET
data = excluded.data,
fetched_at = excluded.fetched_at
RETURNING id, data, fetched_at
`

func (q *Queries) SaveModelCatalog(ctx context.Context, data string) (ModelCatalog, error) {
	row := q.db.QueryRowContext(ctx, saveModelCatalog, data)
	var i ModelCatalog
	err := row.Scan(&i.ID, &i.Data, &i.FetchedAt)
	return i, err
}
