// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddSessionCost(ctx context.Context, arg AddSessionCostParams) (int64, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error)
	// A version the session already holds for the path inserts nothing and
	// returns no row, which callers read as a conflict.
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	// Inserts the path's next version, computed in the same statement so a
	// concurrent writer cannot take it in between.
	CreateFileNextVersion(ctx context.Context, arg CreateFileNextVersionParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteMessage(ctx context.Context, id string) error
	// Deletes the anchor message and every message after it in the session,
	// in the order ListMessagesBySession reads them, as one statement.
	DeleteMessagesFrom(ctx context.Context, arg DeleteMessagesFromParams) ([]Message, error)
	DeleteSession(ctx context.Context, id string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetCheckpointByMessage(ctx context.Context, messageID string) (Checkpoint, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	// Only the provider and model of the last assistant message are read;
	// skip fetching the parts blob and the rest of the row.
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (GetLastAssistantMessageBySessionRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetModelCatalog(ctx context.Context) (ModelCatalog, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListCheckpointsBySession(ctx context.Context, sessionID string) ([]Checkpoint, error)
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListFilesBySessionWithChildren(ctx context.Context, arg ListFilesBySessionWithChildrenParams) ([]File, error)
	// created_at has whole-second resolution and a prompt and its reply
	// often share a second; rowid is insertion order and breaks the tie.
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionFrom(ctx context.Context, arg ListMessagesBySessionFromParams) ([]Message, error)
	// The prompt-history entries of user messages, newest message first: each
	// text part as written and each shell command prefixed with "!", read
	// straight from the stored parts so no binary attachment or context note
	// is decoded. An empty session_id reads every session.
	ListPromptHistory(ctx context.Context, sessionID interface{}) ([]ListPromptHistoryRow, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	// Adds a step's cost and replaces whichever token counter the step
	// measured (NULL leaves a counter alone), in one statement so a concurrent
	// rename or sub-agent cost roll-up is never overwritten.
	RecordSessionUsage(ctx context.Context, arg RecordSessionUsageParams) (Session, error)
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SaveModelCatalog(ctx context.Context, data string) (ModelCatalog, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	// Writes the compaction pointers, and the token counters when given,
	// leaving title, cost and todos to their own writers.
	UpdateSessionCompaction(ctx context.Context, arg UpdateSessionCompactionParams) (Session, error)
	UpdateSessionGoal(ctx context.Context, arg UpdateSessionGoalParams) error
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
