// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddSessionCost(ctx context.Context, arg AddSessionCostParams) (int64, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteMemory(ctx context.Context, id string) (int64, error)
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetCheckpointByMessage(ctx context.Context, messageID string) (Checkpoint, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetLatestFileVersion(ctx context.Context, path string) (int64, error)
	GetMemory(ctx context.Context, id string) (Memory, error)
	GetMemoryByTitle(ctx context.Context, lower string) (Memory, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetModelCatalog(ctx context.Context) (ModelCatalog, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListCheckpointsBySession(ctx context.Context, sessionID string) ([]Checkpoint, error)
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListFilesBySessionWithChildren(ctx context.Context, arg ListFilesBySessionWithChildrenParams) ([]File, error)
	// The id tie-breaks: updated_at has whole-second resolution, so
	// memories saved in the same second would otherwise come back in
	// whatever order SQLite chose, and the index the model reads would
	// reshuffle between runs.
	ListMemories(ctx context.Context) ([]Memory, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionFrom(ctx context.Context, arg ListMessagesBySessionFromParams) ([]Message, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ReapMemories(ctx context.Context, limit int64) (int64, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SaveModelCatalog(ctx context.Context, data string) (ModelCatalog, error)
	TouchMemory(ctx context.Context, id string) error
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
