name: Update generated files

on:
  push:
    branches: [main]
    paths:
      - "internal/config/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - run: go run . schema > ./schema.json

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: regenerate schema.json"
          branch: main
